import './globals.css'
import { Inter } from 'next/font/google'
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Encuesta LABTEC',
//   description: 'Generated by create next app',
// }

const firebaseConfig = {
  apiKey: "AIzaSyBgCpIERt6fljTOmCUxvIKnINjGHpEpkL4",
  authDomain: "labtec-encuesta.firebaseapp.com",
  projectId: "labtec-encuesta",
  storageBucket: "labtec-encuesta.appspot.com",
  messagingSenderId: "356192607920",
  appId: "1:356192607920:web:0da7f45bc4f6917378a575"
};


export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app)
export const auth = getAuth(app);


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className='flex items-center justify-center h-full px-3 py-2 mx-auto max-w-7xl'>
          {children}
        </main>
      </body>
    </html>
  )
}
