import { Footer } from '@/components/Footer';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Encuesta LABTEC',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-center justify-center relative`}>
        <main className='w-full h-screen px-3 py-2 mx-auto max-w-7xl'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
