export const preguntas: string[] = [
    "¿Tuvo fiebre en las últimas 48 hs?",
    "¿Tiene gripe?",
    "¿Tiene Asma Bronquial?",
    "¿Tiene Amigdalitis?",
    "¿Tiene Bronquitis Aguda?",
    "¿Tiene Laringitis?",
    "¿Tiene Neumonía?",
    "¿Tiene otitis media aguda severa?",
    "¿Tiene Vértigo (mareos) moderado o severo que le altera la marcha normal al caminar?",
    "¿Tiene Cefalea (dolor de cabeza) moderado o intenso que no cedió con antimigrañosos en las últimas 24 hs?",
    "¿Tiene alteraciones en el equilibrio?",
    "¿Tiene pérdida de fuerza y/o de movilidad en algún miembro (superior o inferior)?",
    "¿Tiene alteraciones evidentes para hablar o articular palabras de reciente comienzo (menor de 24hs)?",
    "¿Tiene signos de Parálisis Facial (agrandamiento de un ojo sin posibilidad de parpadear, lagrimeo persistente, desviación de una comisura labial hacia un lado)?",
    "¿Tiene Glaucoma (Hipertensión ocular)?",
    "¿Tiene antecedentes de Epilepsia o convulsiones de otra causa no declarada hasta ahora?",
    "¿Tuvo desmayos de cualquier causa sufridos 24 hs antes de tener que subir al sitio?",
    "¿Tuvo accidentes domésticos que impidan manualizar y/o caminar?",
    "¿Tiene heridas cortantes que requirieron sutura?",
    "¿Tiene esguinces moderados o severos?",
    "¿Tiene Amputaciones de cualquier tipo (aún leves)?",
    "¿Tiene desgarros musculares y/o tendinitis de cualquier tipo y ubicación?",
    "¿Tiene fracturas de cualquier naturaleza y ubicación?",
    "¿Tiene lumbalgias persistentes > 48 hs previas a la subida al Sitio?",
    "¿Tiene HTA (Hipertensión Arterial)?",
    "¿Tiene dolor de pecho moderado o intenso opresivo mayor de 12 hs de evolución asociado a disnea(falta de aire)?",
    "¿Tiene Hipotension Arterial Severa (TAS < 90 mmHg)?",
    "¿Tiene antecedentes de Trombosis Venosa Arterial?",
    "¿Tiene antecedentes de Arritmias Cardiacas?",
    "¿Tiene Diabetes con tratamiento?",
    "¿Tiene antecedentes de Hipercolesterolemia o Hiperuricemia?",
    "¿Tiene cólico abdominal severo?",
    "¿Tiene Gastroenteritis Aguda (vómitos + diarrea) asociada o no a fiebre?",
    "¿Tiene vómitos persistentes?",
    "¿Tiene Hemorroides agudas sintomáticas?",
    "¿Tiene enfermedades ginecológicas?",
    "¿Tiene Infecciones Urinarias/Urogenitales?",
    "¿Tiene alergia de tipo dérmica?",
    "¿Tiene alergia a algún medicamento?",
    "¿Tiene alergias respiratorias (rinitis alérgica, asma alérgico)?",
    "¿Tiene alergia a plantas o insectos?",
    "¿Es celíaco/a?",
    "¿Tiene alergia a algún alimento?",
    "¿Tiene alguna otra patología?",
    "Peso Actual (en kg)",
    "Edad",
    "Altura (en cm)",
    "¿Realizó la capacitación en Mal Agudo de Montaña?",
];
